### PR TITLE
Ensure only one deploy runs at a time.

### PR DESCRIPTION
**Pull request by jmcarp**
Terraform state locking will make this less of an issue once we upgrade
to the latest version.

### CODE REVIEW

**Comment by datn** [comment]
Briefly educating myself on this topic for the purposes of this review.

**Comment by datn** [comment]
Got it, makes sense.

**Comment by jmcarp** [comment]
Should be good to merge @datn . We'll have to update the pipeline configuration in concourse for this to take effect.

**Comment by jmcarp** [comment]
@datn: did you have a chance to update the pipeline?

**Comment by datn** [comment]
Going to update it today -- I looked at the existing pipeline first and was a little puzzled by how it differed from GitHub, so later today I'm going to look at it more closely.

**Comment by datn** [comment]
Updated.

**Pull request merged**
