### PR TITLE
plainlanguage.gov must be alias record

### PR DESCRIPTION
**Pull request by amirbey**

### CODE REVIEW

**Review by apburnes — APPROVED** [review]

**Comment by RhettSkelton** [comment]
https://www.plainlanguage.gov/ but our re-direct on https://plainlanguage.gov/ is showing a blank page. Any idea why?

**Comment by amirbey** [comment]
the dns had to be unset and reset to point to redirects app ... the dns
change for plainlanguage.gov is in progress at this moment

**Comment by RhettSkelton** [comment]
Thanks for the explanation.

**Comment by amirbey** [comment]
https://github.com/18F/dns/pull/489 failed to apply but working on resolution ...

**Pull request merged**
