### PR TITLE
Update api.open.fec.gov and api-stage.open.fec.gov CNAMEs for api.data.gov

### PR DESCRIPTION
**Pull request by GUI**
See: https://github.com/fecgov/openFEC/issues/3293

api.data.gov is completing some underlying service changes, so we've asked some agencies to update CNAMEs they had pointing to our infrastructure. Since these domains appears to be managed here for FEC (yay!), I thought I'd go ahead and submit a pull request for this change, but let us know if there's actually a different process for this.

The current CNAME of api-open-fec-2086140464.us-east-1.elb.amazonaws.com is an ELB that the api.data.gov service owns, and we'd instead like these to point to api-open-fec-gov.domains.api.data.gov (which currently resolve to the same IPs, but this switch will allow us to complete some underlying api.data.gov upgrades without further CNAME switches).

Let me know if you have any questions or we need to do anything else. Thanks!

### CODE REVIEW

**Comment by patphongs** [comment]
@GUI Checking in on this PR. Looks like it hasn't been merged yet and still pending someone over at 18F to review? The deadline for the update was by August 1st, so I wanted to make sure the API umbrella would still be ok if this wasn't merged in by 8/1?

**Comment by afeld** [comment]
Will wait for a go-ahead from someone on the FEC team.

**Comment by afeld** [comment]
Ah, looks like we got one: https://github.com/fecgov/openFEC/issues/3293#issuecomment-407082706

**Comment by patphongs** [comment]
Thanks @afeld !

**Pull request merged**
