### PR TITLE
Redirect emerging.digital.gov

### PR DESCRIPTION
**Pull request by saracope**
Redirect https://emerging.digital.gov/ to https://digital.gov/topics/emerging-tech/

### CODE REVIEW

**Comment by amirbey** [comment]
hi @saracope 
1) the PR looks good .. however, unfortunately redirecting the DNS settings for a domain in the same PR doesn't works too well.  On Tuesday, the same exact steps were taken in 1 PR and 18f/dns deploy failed in circleci and took a bunch of work to resolve..  For a smooth experience to perform this redirect, I'd recommend 1 PR to remove the domain, and then a 2nd PR to add the redirect.
2) @afeld prefers we use https://github.com/18f/pages-redirects to perform redirects and plans to move away from doing it in 18f/dns via the modue.  Can you close this PR and raise one in https://github.com/18f/pages-redirects instead?

**Comment by saracope** [comment]
@amirbey The readme for this repo says "We are moving from pages-redirects to fully configuring them in this repository. " 
@afeld Can you clarify?

**Comment by afeld** [comment]
@saracope Sorry for the confusion. It's kind of in the middle right now; you can use either the module (as a two-step thing, like @amirbey suggested), or stick with pages-redirects. Does that make sense?

**Comment by afeld** [comment]
https://github.com/18F/pages-redirects/issues/149 is the next major step to improve redirects.

**Comment by saracope** [comment]
@afeld Is this within the scope of the Tech portfolio to do? I would love to just put in a ticket request for this sort of thing to have the people who know how to do it the preferred/right way actually do it the right away instead of blundering around.

**Pull request closed without merging**
