### PR TITLE
remove Open Opportunities records

### PR DESCRIPTION
**Pull request by afeld**
digitalgov.gov (minus www.digitalgov.gov) is using GSA's nameservers, not Route 53, so these records aren't actually in use / being managed by Terraform. In other words, this will have no effect on live site(s). Cleaning up the cruft.

### CODE REVIEW

**Comment by afeld** [comment]
Nope, shouldn't be.

**Comment by konklone** [comment]
@afeld Unfortunately, this wasn't correct. Digitalgov.gov has been managed by GSA IT's DNS servers, but the records for `openopps.digitalgov.gov` were NS re-delegations, set by GSA IT, to this Terraform-backed R53 account. So this broke openopps.digitalgov.gov.

I recommend restoring the CNAME record to `digitalgov.gov.tf` **after** the NS switch for the whole `digitalgov.gov` zone is complete.

**Comment by konklone** [comment]
@afeld On second thought -- actually, not so sure. I would have expected the Terraform zone to be `openopps.digitalgov.gov.tf` if this were tracking the delegation from GSA IT. 

But either way, the records GSA IT had set for `openopps` in the `digitalgov.gov` zone were/are:

```

ns-1231.awsdns-25.org.
ns-452.awsdns-56.com.
ns-788.awsdns-34.net.
ns-1886.awsdns-43.co.uk.
```

**Comment by wslack** [comment]
Just to retro this very quickly, how should we change procedure based on this PR and its impact (if at all?)

**Comment by afeld** [comment]
> I would have expected the Terraform zone to be `openopps.digitalgov.gov.tf`

Terraform file naming is arbitrary, just FYI. We just have a convention of naming files as whatever the top-level domain is that is delegated / pointed to that public zone in Route 53. Agreed that if OpenOpps (only) were delegated, the public zone should have been `openopps.digitalgov.gov` and the filename `openopps.digitalgov.gov.tf`. (Maybe that's what you meant! Sorry for 'splaining if so.)

> the records GSA IT had set for `openopps` in the `digitalgov.gov` zone were/are: `ns-1231.awsdns-25.org.` ...

Yeah, they weren't at the time.

> how should we change procedure based on this PR

Wrote up my idea in #176.

**Pull request merged**
