### PR TITLE
Add CNAME and TXT records to allow Zendesk to send emails from domain

### PR DESCRIPTION
**Pull request by lsamuels-fearless**
PRs affecting a Federalist site must receive approval from a member of the relevant team.

Zendesk requests that we add CNAME and TXT records to support their ability to send from the support.digitalgov.gov domain.

See here for details:
[](https://support.zendesk.com/hc/en-us/articles/203683886-Setting-up-SPF-for-Zendesk-to-send-email-on-behalf-of-your-email-domain)

### CODE REVIEW

**Comment by afeld** [comment]
Is this still desired? cc @jeremyzilar

**Comment by lsamuels-fearless** [comment]
Yes please. It is needed for our helpdesk software email integration.

**Comment by jeremyzilar** [comment]
@lsamuels-fearless I added in a few comments. Let me know if you have Qs. Happy to 👀

**Comment by its-a-lisa** [comment]
Is this still desired? cc @jeremyzilar

**Comment by jeremyzilar** [comment]
Checking with the Search.gov team @its-a-lisa.

**Comment by jeremyzilar** [comment]
@lsamuels-fearless confirmed that this can go up.

**Comment by jeremyzilar** [comment]
Closing this, and will add these records to a new PR, based off the re-organized file we made in
https://github.com/18F/dns/pull/385

**Pull request closed without merging**
