### PR TITLE
[WIP] adding in the record for demo.digitalgov.gov as well

### PR DESCRIPTION
**Pull request by jeremyzilar**
might as well have all of the DG domains managed in the same way

PRs affecting cloud.gov.tf or a Federalist site must receive approval from a member of the relevant team.

### CODE REVIEW

**Comment by wslack** [comment]
@jeremyzilar how was this DNS managed before?

**Comment by jeremyzilar** [comment]
@wslack This terraform file was already, here, I just added in the record for demo.digitalgov.gov.

**Comment by wslack** [comment]
right - I'm saying that demo.digitalgov.gov already works; DNS is already set somewhere - I don't want to add DNS config here unless its removed elsewhere

**Comment by wslack** [comment]
@jeremyzilar ready to merge this as well?

**Comment by wslack** [comment]
should this be closed?

**Pull request closed without merging**
