### PR TITLE
data.gov - updating dns

### PR DESCRIPTION
**Pull request by robert-bryson**
Related to https://github.com/gsa/datagov-deploy/issues/1001

This PR configures data.gov DNS to use 18f/dns in the near future. 

In order to configure DNSSEC, the `aws_route53_hosted_zone_dnssec` resource is need from [terraform-provider-aws](https://github.com/hashicorp/terraform-provider-aws). [It was introduced](https://github.com/hashicorp/terraform-provider-aws/blob/26ca7e0b94cdd1baea3e651e77bddf3aaaca2d2e/CHANGELOG.md#3310-march-04-2021) in `3.31.0` so this PR updates the version currently used by [18f/dns](https://github.com/18F/dns/blob/ee933a6bba381ffccafd194b49c5541a3d551fe1/terraform/init.tf#L9) (`3.30.0`) one minor version. 

`3.30.0` was released in March 2021, the [current version](https://github.com/hashicorp/terraform-provider-aws/blob/26ca7e0b94cdd1baea3e651e77bddf3aaaca2d2e/CHANGELOG.md#3740-january-28-2022) is `3.74.0`. 

---
Data.gov is not a new site, so I believe the section below is not relevant.
- [ ] This is a new public-facing site _(if so, please follow the additional instructions below)_
   - [ ] Provide context
   - [ ] Assign to `@18F/osc` for review
   - [ ] [TTS Digital Council's new site review process](https://docs.google.com/document/d/1j6eieL3oop0rxCAldVVh7uGdOCG-ajafrog_BZ-u470/edit) completed
   - [ ] Update [the inventory](https://docs.google.com/spreadsheets/d/1OBO6g7_OsVBv0vG8WSCI6L2FD_iRh3A7a_6eQWj2zLE/edit?ts=6025575d#gid=2013137748) with new site information

### CODE REVIEW

**Comment by robert-bryson** [comment]
Generation script gist at https://gist.github.com/robert-bryson/58351b0cd691ae002853fb68348e1b1a

**Review by JJediny — APPROVED** [review]
Changes and minor upgrade look good. @mogul ready to merge?

**Comment by mogul** [comment]
@JJediny yup, let's do it.

**Comment by davemcorwin** [comment]
@robert-bryson @JJediny This deployment failed...https://app.circleci.com/pipelines/github/18F/dns/425/workflows/a1499d94-2262-4ad8-8377-affeccc8ee99/jobs/1672

**Comment by robert-bryson** [comment]
> @robert-bryson @JJediny This deployment failed...https://app.circleci.com/pipelines/github/18F/dns/425/workflows/a1499d94-2262-4ad8-8377-affeccc8ee99/jobs/1672

Thanks for the heads up!

Working on a fix with https://github.com/18F/dns/pull/569

**Pull request merged**
